{
  description = "Logos Workspace — unified multi-repo development environment";

  # ── Inputs ─────────────────────────────────────────────────────────────────
  #
  # The bulk of this block is auto-generated by `ws sync-graph` from each
  # repo's flake.lock.  Nix's flake parser requires `inputs` to be a literal
  # attrset (no `let`, `//`, `import`, or `builtins.mapAttrs` allowed), so
  # the per-repo follows can't be computed at evaluation time — they must
  # be written into this file directly.
  #
  # To regenerate after editing any repo's flake inputs:
  #
  #     ws sync-graph
  #
  # URL overrides (logos-blockchain org, tutorial sub-flakes) and manual
  # follows overrides live in `scripts/ws` near the top of `cmd_sync_graph`.

  inputs = {
    # ── Manual: shared Nix infrastructure ──────────────────────────────────
    #
    # logos-nix pins the workspace's nixpkgs (and therefore Qt).  Overriding
    # logos-nix here propagates to ALL downstream consumers via the auto-
    # generated follows below.
    # fleet-kit: pinned to the logos-fleet fork at an explicit rev; pin.sh moves the rev
    # to the repos/logos-nix gitlink (this manual input is skipped by `ws sync-graph`).
    logos-nix.url = "github:logos-fleet/logos-nix/fc87e23b8432675a8de5c61c50e319d7582749ce";
    nixpkgs.follows = "logos-nix/nixpkgs";
    # Pinned explicitly because logos-blockchain-module's upstream lock
    # currently references an invalid commit-ish via /0.2.1.
    logos-blockchain.url = "github:logos-blockchain/logos-blockchain/88941ff33f2e028591b9d0ed2549a328d54f0cfa";

    # BEGIN AUTO-INPUTS — generated by `ws sync-graph`, do not edit by hand
    logos-protocol = {
      url = "github:logos-fleet/logos-protocol/ceee02b50c03b96e218465ac610351c3213f259a";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-qt-sdk = {
      url = "github:logos-fleet/logos-qt-sdk/b2ebecc0b7fb6a801dfbde9df60525a0c6dc0a82";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-cpp-sdk = {
      url = "github:logos-fleet/logos-cpp-sdk/41ca4491f0163e0735511b6ac7d9020dec88a84c";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-view-module-runtime = {
      url = "github:logos-fleet/logos-view-module-runtime/b4d91ff5185ccfd6e0940e12bb9a811bee8b8c84";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module-client = {
      url = "github:logos-fleet/logos-module-client/351f282055659a9d8ccf0e6411c2683256906958";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-qt-sdk.follows = "logos-qt-sdk";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module = {
      url = "github:logos-fleet/logos-module/3120dd231ab799e9fe8ace4ae8fe008228cb9a41";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-liblogos = {
      url = "github:logos-fleet/logos-liblogos/da49ecd7923eea6dfed9932fa448286ae3cee184";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-qt-sdk.follows = "logos-qt-sdk";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.process-stats.follows = "process-stats";
    };
    logos-logoscore-cli = {
      url = "github:logos-fleet/logos-logoscore-cli/6248a746789027e30fdf9256a952c73b18be71c9";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package-downloader-module.follows = "logos-package-downloader-module";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.logos-package-manager-module.follows = "logos-package-manager-module";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-test-modules.follows = "logos-test-modules";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-capability-module = {
      url = "github:logos-fleet/logos-capability-module/ecdc1975dd5f90a834b6d128357414dc60ad7aea";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-package = {
      url = "github:logos-fleet/logos-package/44a31b313e6c057997fb96ba802826f26e2b3a60";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-plugin-qt = {
      url = "github:logos-fleet/logos-plugin-qt/e06545463e9d21ba6fcdd57bee15065643b419a6";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module-builder = {
      url = "github:logos-fleet/logos-module-builder/4a8fe09a07b979c0236d6da36cf21167d83bac53";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-design-system.follows = "logos-design-system";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-plugin-core.follows = "logos-plugin-qt";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-qt-sdk.follows = "logos-qt-sdk";
      inputs.logos-rust-sdk.follows = "logos-rust-sdk";
      inputs.logos-standalone-app.follows = "logos-standalone-app";
      inputs.logos-view-module-runtime.follows = "logos-view-module-runtime";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-dir = {
      url = "github:logos-fleet/nix-bundle-dir/ffc410b7f2bab32b1c2ceb347c56902e7321049c";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-lgx = {
      url = "github:logos-fleet/nix-bundle-lgx/d0828e0bf28f9714d066f260bad281681293686d";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-appimage = {
      url = "github:logos-fleet/nix-bundle-appimage/04a3cf89f8ba3dc20f08a8e2b6c337a672bceda7";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-macos-app = {
      url = "github:logos-fleet/nix-bundle-macos-app/d6b0cc518e599ab7a52258bf3e1f8123c8a01d31";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-standalone-app = {
      url = "github:logos-fleet/logos-standalone-app/1aa90d083c03679de1e2f0291adb818032d044fc";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-design-system.follows = "logos-design-system";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-qt-sdk.follows = "logos-qt-sdk";
      inputs.logos-view-module-runtime.follows = "logos-view-module-runtime";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-basecamp = {
      url = "github:logos-fleet/logos-basecamp/8cd94656e64485fb8e86cd8f495c261f9c204d89";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-design-system.follows = "logos-design-system";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.logos-package-downloader-module.follows = "logos-package-downloader-module";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.logos-package-manager-module.follows = "logos-package-manager-module";
      inputs.logos-package-manager-ui.follows = "logos-package-manager-ui";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-qt-sdk.follows = "logos-qt-sdk";
      inputs.logos-view-module-runtime.follows = "logos-view-module-runtime";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nix-bundle-macos-app.follows = "nix-bundle-macos-app";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-accounts-module = {
      url = "github:logos-fleet/logos-accounts-module/4fd4cb0be3d281b4a9b3303f892b2b265edb2a62";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-accounts-ui = {
      url = "github:logos-fleet/logos-accounts-ui/324b2c6e0aa76ecbed3a2d2922fd16093539eb25";
      inputs.accounts_module.follows = "logos-accounts-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-chat-module = {
      url = "github:logos-fleet/logos-chat-module/33c624d0e6ea8444486d6bfe68aa07450315bdb6";
      inputs.logos-delivery-module.follows = "logos-delivery-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-chat-ui = {
      url = "github:logos-fleet/logos-chat-ui/8d6a9feaa6eef3e9714d3aed3867d20337972542";
      inputs.chat_module.follows = "logos-chat-module";
      inputs.logos-delivery-module.follows = "logos-delivery-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-package-manager = {
      url = "github:logos-fleet/logos-package-manager/e8170abd214ec28dadc3209597552f312e8b9d60";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-package-downloader = {
      url = "github:logos-fleet/logos-package-downloader/00c4e4e6223049eb2a6a45a2786e67913e830397";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-package-manager-module = {
      url = "github:logos-fleet/logos-package-manager-module/6f2b84fce9a8730d4d2599f1442fa7effcb672dd";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-package-manager.follows = "logos-package-manager";
    };
    logos-package-downloader-module = {
      url = "github:logos-fleet/logos-package-downloader-module/917cf3cb12a2b0b9f04ecfcb81fdc3402519f1e4";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-package-downloader.follows = "logos-package-downloader";
    };
    logos-package-manager-ui = {
      url = "github:logos-fleet/logos-package-manager-ui/d14f284ea73e47448bebc6841612e53123c585bb";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-package.follows = "logos-package";
      inputs.package_downloader.follows = "logos-package-downloader-module";
      inputs.package_manager.follows = "logos-package-manager-module";
    };
    logos-storage-module = {
      url = "github:logos-fleet/logos-storage-module/8feb7cc0f7806bc2b25faa884e1bb9076b993969";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-storage-ui = {
      url = "github:logos-fleet/logos-storage-ui/823be657d236afe824b9804d6aee69c14b1d4507";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.storage_module.follows = "logos-storage-module";
    };
    logos-wallet-module = {
      url = "github:logos-fleet/logos-wallet-module/f6f9c160410db824531f42dd8b27ccecd39ca589";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-wallet-ui = {
      url = "github:logos-fleet/logos-wallet-ui/26f8f5bebd511e91e29019e1e7c892bd5753439d";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.wallet_module.follows = "logos-wallet-module";
    };
    logos-delivery-module = {
      url = "github:logos-fleet/logos-delivery-module/3f8a0ed99afae349fec8013442638e7569ac2cf3";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    logos-delivery-demo = {
      url = "github:logos-fleet/logos-delivery-demo/b5fec54843a20290fdc847762bdbc7f2d7217da1";
      inputs.delivery_module.follows = "logos-delivery-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-blockchain-module = {
      url = "github:logos-fleet/logos-blockchain-module/581323e9e587a3b8057f8f63a9ade1ff1892111a";
      inputs.logos-blockchain.follows = "logos-blockchain";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-blockchain-ui = {
      url = "github:logos-fleet/logos-blockchain-ui/eb513b5a79f558f5718a5ca0eafac1d5fda7d832";
      inputs.blockchain_module.follows = "logos-blockchain-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    logos-execution-zone-wallet-ui = {
      url = "github:logos-fleet/logos-execution-zone-wallet-ui/da1b021db5315eccd1e39835268bbc08633adc12";
      inputs.lez_core.follows = "logos-execution-zone-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    logos-execution-zone-module = {
      url = "github:logos-fleet/logos-execution-zone-module/033f807a3b1690fb2f8e661cb8067646b8a98242";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    logos-libp2p-module = {
      url = "github:logos-fleet/logos-libp2p-module/7b4b776b26d96e2a0c794827c77bb6eb89da5100";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logoscore-cli.follows = "logos-logoscore-cli";
      inputs.package-manager.follows = "logos-package-manager";
      inputs.libp2p.url = "github:vacp2p/nim-libp2p/7c73484cc0c57a5f649dd3d277cef1c7c4de28f0";
    };
    logos-webview-app = {
      url = "github:logos-fleet/logos-webview-app/b5d1bb40da6ba550076069a10cf9beaac45aa515";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    counter_qml.url = "github:logos-fleet/counter_qml/8029a894f4221f9284efabbedcee7d9d18929777";
    counter = {
      url = "github:logos-fleet/counter/204ec0d3f0ccffc5d40269db9e7253cba7c330d6";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-design-system = {
      url = "github:logos-fleet/logos-design-system/fd4978713921e087c40f4a6a52a3e5f60f6104bd";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nix-bundle-macos-app.follows = "nix-bundle-macos-app";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-js-sdk = {
      url = "github:logos-fleet/logos-js-sdk/56be2d4a52ab5b7e524f22a175b3b8498d9c568c";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-nim-sdk = {
      url = "github:logos-fleet/logos-nim-sdk/df1f21906e661d96f5e4bda172cb9a619292b603";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-rust-sdk.url = "github:logos-fleet/logos-rust-sdk/bbfb42ff732f6858bb9459e935bd4170a83804bf";
    logos-logoscore-py = {
      url = "github:logos-fleet/logos-logoscore-py/6e081b2d2fd87a909b958aa8a97be445229acf75";
      inputs.logos-logoscore-cli.follows = "logos-logoscore-cli";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-test-modules.follows = "logos-test-modules";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-test-modules = {
      url = "github:logos-fleet/logos-test-modules/3725a1a3226301d2ca8b51bb6a690e20b326fd01";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-logoscore-cli.follows = "logos-logoscore-cli";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    process-stats = {
      url = "github:logos-fleet/process-stats/28ae028320139beccb95340a8b4a341364d1601e";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module-viewer = {
      url = "github:logos-fleet/logos-module-viewer/b6489c1aab8c1590fa127dbaedb39708f3614fbc";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-evm-net-proxy.url = "github:logos-fleet/logos-evm-net-proxy/564a730551b677ff8292144c3773a46d99a18b91";
    logos-evm-keystore-module = {
      url = "github:logos-fleet/logos-evm-keystore-module/1ac386973acf568b48bb52f7e17baf302fa55670";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-eth-rpc-module = {
      url = "github:logos-fleet/logos-evm-eth-rpc-module/8a825cdbf0b78de4af30b6250e91b08d2e1ba1d7";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-token-list-module = {
      url = "github:logos-fleet/logos-evm-token-list-module/25d5d6b2a96987bb2a757a0348c150baeb675e3b";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-uniswap-module = {
      url = "github:logos-fleet/logos-evm-uniswap-module/df069a7eab47d705eb3b519092a5e41e85ddd7f1";
      inputs.eth_rpc_module.follows = "logos-evm-eth-rpc-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-railgun-module = {
      url = "github:logos-fleet/logos-evm-railgun-module/b6d066932c62791c8be5b9a7344318d8df9a6156";
      inputs.eth_rpc_module.follows = "logos-evm-eth-rpc-module";
      inputs.keystore_module.follows = "logos-evm-keystore-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-wallet-backend-module = {
      url = "github:logos-fleet/logos-evm-wallet-backend-module/584dbfe3195ec6dfe4c0d8b91fabb02ac2d963f4";
      inputs.eth_rpc_module.follows = "logos-evm-eth-rpc-module";
      inputs.keystore_module.follows = "logos-evm-keystore-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.railgun_module.follows = "logos-evm-railgun-module";
      inputs.token_list_module.follows = "logos-evm-token-list-module";
      inputs.uniswap_module.follows = "logos-evm-uniswap-module";
    };
    logos-evm-wallet-ui = {
      url = "github:logos-fleet/logos-evm-wallet-ui/68f7c4fe6005990dea38de67d6853d12d9045872";
      inputs.eth_rpc_module.follows = "logos-evm-eth-rpc-module";
      inputs.keystore_module.follows = "logos-evm-keystore-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.railgun_module.follows = "logos-evm-railgun-module";
      inputs.token_list_module.follows = "logos-evm-token-list-module";
      inputs.uniswap_module.follows = "logos-evm-uniswap-module";
      inputs.wallet_backend_module.follows = "logos-evm-wallet-backend-module";
    };
    # END AUTO-INPUTS
  };

  outputs = { self, nixpkgs, ... }@inputs:
    let
      systems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forAllSystems = fn: nixpkgs.lib.genAttrs systems fn;

      depGraph = import ./nix/dep-graph.nix;

      # Every logos flake input we iterate over for packages/apps/checks.
      # Excludes `logos-nix` (it's a nixpkgs pin, not a buildable repo).
      repoInputNames = builtins.attrNames
        (builtins.removeAttrs depGraph [ "logos-nix" ]);

      # Mapping from flake input name → submodule directory name under repos/.
      # Only entries where the names differ need to be listed.
      inputToDirOverrides = {
        "logos-calc-module" = "logos-tutorial/logos-calc-module";
        "logos-calc-ui"     = "logos-tutorial/logos-calc-ui";
        "logos-calc-ui-cpp" = "logos-tutorial/logos-calc-ui-cpp";
      };

      inputToDir = name: inputToDirOverrides.${name} or name;

    in {

      # ── Packages ──────────────────────────────────────────────────────────
      # nix build .#logos-cpp-sdk          → default package
      # nix build .#logos-basecamp          → default package
      # nix build .#logos-basecamp--portable → non-default output
      # nix build .#logos-liblogos--portable
      # nix bundle --bundler .#nix-bundle-lgx .#logos-chat-module--lib
      # All repo package outputs are exposed: default as the repo name,
      # non-default as <repo>--<output>.
      packages = forAllSystems (system:
        let
          # Collect all package outputs from all repos.
          # Each repo's packages are forwarded lazily — the value is not
          # evaluated until someone actually builds it, so broken store
          # paths or missing files won't cause errors at evaluation time.
          allPkgs = builtins.foldl' (acc: name:
            let
              repoPkgs = (inputs.${name}.packages.${system} or {});
              outNames = builtins.attrNames repoPkgs;
            in
            acc // builtins.listToAttrs (map (outName:
              let
                attrName = if outName == "default" then name else "${name}--${outName}";
              in
              { name = attrName; value = repoPkgs.${outName}; }
            ) outNames)
          ) {} repoInputNames;
        in allPkgs
      );

      # ── Apps ──────────────────────────────────────────────────────────────
      # nix run .#logos-standalone-app -- --plugin ./result/lib/
      # Forwards apps outputs from all repos. Default app exposed as repo name,
      # non-default as <repo>--<output>.
      apps = forAllSystems (system:
        builtins.foldl' (acc: name:
          let
            repoApps = (inputs.${name}.apps.${system} or {});
            outNames = builtins.attrNames repoApps;
          in
          acc // builtins.listToAttrs (map (outName:
            let
              attrName = if outName == "default" then name else "${name}--${outName}";
            in
            { name = attrName; value = repoApps.${outName}; }
          ) outNames)
        ) {} repoInputNames
      );

      # ── Dev Shells ────────────────────────────────────────────────────────
      # nix develop          → workspace shell (ws CLI + common tools)
      # nix develop .#logos-cpp-sdk → that repo's own devShell
      # nix develop          → workspace shell with ws CLI + common tools
      # For sub-repo devShells use: nix develop path:./repos/<repo-name>
      #   or: ws develop <repo-name>
      devShells = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; };
          # Always delegates to the live scripts/ws in the workspace,
          # without needing to rebuild the devshell. Falls back to the
          # flake directory if LOGOS_WORKSPACE_ROOT is not set.
          wsScript = pkgs.writeShellScriptBin "ws" ''
            exec "''${LOGOS_WORKSPACE_ROOT:-${builtins.toString ./.}}/scripts/ws" "$@"
          '';
        in {
          default = import ./nix/devshell.nix { inherit pkgs wsScript; };
        }
      );

      # ── Checks ────────────────────────────────────────────────────────────
      # nix flake check        → run ALL repo checks
      # nix build .#checks.x86_64-linux.logos-cpp-sdk--test
      checks = forAllSystems (system:
        builtins.foldl' (acc: name:
          let
            result = builtins.tryEval (inputs.${name}.checks.${system} or {});
            repoChecks = if result.success then result.value else {};
            prefixed = nixpkgs.lib.mapAttrs'
              (cname: drv: { name = "${name}--${cname}"; value = drv; })
              repoChecks;
          in
          acc // prefixed
        ) {} repoInputNames
      );

      # ── Bundlers ──────────────────────────────────────────────────────────
      # Forwards nix-bundle-lgx bundlers so scripts can use "$WORKSPACE_ROOT"
      # as the --bundler reference.
      bundlers = forAllSystems (system:
        inputs.nix-bundle-lgx.bundlers.${system}
      );

      # ── Lib (for programmatic use) ────────────────────────────────────────
      lib = {
        inherit repoInputNames inputToDir;
        # Dependency graph: input name → { deps, follows, hasTests }
        depGraph = depGraph;
      };
    };
}
